[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib']
test = 'test/foundry'
cache = true

optimizer = true
optimizer_runs = 4294967295
bytecode_hash = 'none'
sparse_mode = true
ignored_error_codes = [3860, 5574]

verbosity = 2
ffi = false

[fuzz]
runs = 256
seed = "42"

[profile.ci]
optimizer_runs = 200

[profile.ci.fuzz]
runs = 16

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
